# -*- coding: utf-8 -*-
"""StyleHue

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SD5rYa67JLuemCzHYxXjrqGsraPm9Czm
"""

# 🎨 StyleHue – AI Outfit Color Analyzer

# Step 1: Define color theory logic
color_families = {
    'red': ['green', 'blue', 'white'],
    'blue': ['orange', 'white', 'yellow'],
    'green': ['red', 'black', 'beige'],
    'yellow': ['blue', 'black', 'navy'],
    'pink': ['white', 'navy', 'grey'],
    'white': ['any'],
    'black': ['any'],
    'grey': ['pink', 'red', 'white'],
    'beige': ['brown', 'black', 'blue'],
    'brown': ['beige', 'cream', 'orange'],
    'orange': ['blue', 'white', 'green'],
    'navy': ['white', 'pink', 'beige'],
    'cream': ['brown', 'maroon', 'navy'],
    'maroon': ['cream', 'grey', 'black'],
    'purple': ['yellow', 'white', 'grey']
}

# Step 2: Analyze input
def analyze_outfit(text):
    text = text.lower()
    detected_colors = []

    # detect known color names
    for color in color_families.keys():
        if color in text:
            detected_colors.append(color)

    if not detected_colors:
        return "❌ No recognizable fashion colors found. Try entering: 'blue jeans and white shirt' etc."

    suggestions = []
    if len(detected_colors) == 1:
        base = detected_colors[0]
        match = color_families[base]
        if match == ['any']:
            return f"✅ Your outfit with **{base}** is neutral – goes with anything! Stylish simplicity."
        return f"🧠 Detected base color: **{base}**\n💡 Try adding: {', '.join(match)} for balance or pop."
    else:
        return f"🎨 Colors Detected: {', '.join(detected_colors)}\n✅ Looks balanced according to color theory!"

# Step 3: Ask for outfit
print("👕 Welcome to StyleHue – Describe your outfit below:")
user_input = input("📝 What are you wearing today? (e.g., 'green shirt and beige pants')\n")

# Step 4: Result
result = analyze_outfit(user_input)
print("\n" + result)